from pymongo import MongoClient

client = MongoClient()
db = client.artist_db
collection = db.artist_collection

for post in collection.find({'tags.value': 'dance'}).sort('rating.count', -1).limit(10):
    print(post)

'''
実行結果
{'rating': {'count': 26, 'value': 88}, 'gid': '79239441-bfd5-4981-a70c-55c3f15c1287', '_id': ObjectId('5d21aa7a08fd2f5b6dce9fe0'), 'gender': 'Female', 'type': 'Person', 'sort_name': 'Madonna', 'area': 'United States', 'begin': {'date': 16, 'month': 8, 'year': 1958}, 'id': 89, 'tags': [{'count': 1, 'value': 'dance-pop'}, {'count': 1, 'value': 'electropop'}, {'count': 1, 'value': 'tell me'}, {'count': 1, 'value': 'pop and chart'}, {'count': 1, 'value': 'multiple ipi'}, {'count': 1, 'value': 'electronic'}, {'count': 1, 'value': 'américain'}, {'count': 1, 'value': 'usa'}, {'count': 1, 'value': 'singer'}, {'count': 1, 'value': 'chanteur'}, {'count': 1, 'value': 'american'}, {'count': 4, 'value': 'pop'}, {'count': 1, 'value': 'greatest hits'}, {'count': 1, 'value': 'dance'}], 'name': 'Madonna', 'ended': True}
{'rating': {'count': 23, 'value': 84}, 'aliases': [{'sort_name': 'Björk Gudmundsdottir', 'name': 'Björk Gudmundsdottir'}, {'sort_name': 'Björk Gudmudsdóttir', 'name': 'Björk Gudmudsdóttir'}, {'sort_name': 'Bj rk', 'name': 'Bj rk'}, {'sort_name': 'BjÃ¶rk', 'name': 'BjÃ¶rk'}, {'sort_name': 'Björk Guðmundsdóttir', 'name': 'Björk Guðmundsdóttir'}, {'sort_name': 'Biork', 'name': 'Biork'}, {'sort_name': 'Bjõrk', 'name': 'Bjõrk'}, {'sort_name': 'Bjørk', 'name': 'Bjørk'}, {'sort_name': 'Bjцrk', 'name': 'Bjцrk'}, {'sort_name': 'Bjork', 'name': 'Bjork'}], 'gid': '87c5dedd-371d-4a53-9f7f-80522fb7f3cb', '_id': ObjectId('5d21aa7608fd2f5b6dcdc96a'), 'gender': 'Female', 'type': 'Person', 'sort_name': 'Björk', 'area': 'Iceland', 'begin': {'date': 21, 'month': 11, 'year': 1965}, 'id': 1022, 'tags': [{'count': 1, 'value': 'soundtrack'}, {'count': 2, 'value': 'ambient'}, {'count': 1, 'value': 'islande'}, {'count': 1, 'value': 'trip-hop'}, {'count': 1, 'value': '90s'}, {'count': 1, 'value': 'islandais'}, {'count': 1, 'value': '2000'}, {'count': 3, 'value': 'experimental'}, {'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'idm'}, {'count': 1, 'value': 'rock and indie'}, {'count': 1, 'value': '10s'}, {'count': 2, 'value': 'alternative'}, {'count': 7, 'value': 'icelandic'}, {'count': 1, 'value': 'multiple ipi'}, {'count': 1, 'value': 'baroque pop'}, {'count': 2, 'value': 'jazz'}, {'count': 1, 'value': 'pop'}, {'count': 2, 'value': 'electronica'}, {'count': 1, 'value': '00s'}, {'count': 3, 'value': 'electronic'}, {'count': 3, 'value': 'iceland'}, {'count': 1, 'value': 'art pop'}, {'count': 1, 'value': 'progressive pop'}, {'count': 1, 'value': 'a cappella'}, {'count': 1, 'value': 'trip hop'}, {'count': 1, 'value': 'whimsically inclined'}], 'name': 'Björk', 'ended': True}
{'rating': {'count': 23, 'value': 90}, 'aliases': [{'sort_name': 'Prodigy', 'name': 'Prodigy'}, {'sort_name': 'The Prodigy Vs. The Prodigy', 'name': 'The Prodigy Vs. The Prodigy'}], 'gid': '4a4ee089-93b1-4470-af9a-6ff575d32704', '_id': ObjectId('5d21aa8408fd2f5b6dd0fcab'), 'id': 44954, 'type': 'Group', 'sort_name': 'Prodigy, The', 'area': 'United Kingdom', 'begin': {'year': 1990}, 'tags': [{'count': 6, 'value': 'big beat'}, {'count': 1, 'value': 'english'}, {'count': 3, 'value': 'british'}, {'count': 1, 'value': 'industrial'}, {'count': 1, 'value': 'dance-punk'}, {'count': 2, 'value': 'uk'}, {'count': 2, 'value': 'breakbeat hardcore'}, {'count': 1, 'value': 'electropunk'}, {'count': 1, 'value': 'britannique'}, {'count': 1, 'value': 'electronica'}, {'count': 1, 'value': '2005'}, {'count': 6, 'value': 'electronic'}, {'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'alternative rock'}, {'count': 1, 'value': 'dance and electronica'}, {'count': 1, 'value': 'rave'}, {'count': 2, 'value': 'hardcore'}, {'count': 1, 'value': 'rock'}, {'count': 1, 'value': 'breakbeat'}, {'count': 1, 'value': 'electro'}, {'count': 2, 'value': 'techno'}], 'name': 'The Prodigy', 'ended': True}
{'rating': {'count': 15, 'value': 68}, 'aliases': [{'sort_name': '蕾哈娜', 'name': '蕾哈娜'}, {'sort_name': 'Rhianna', 'name': 'Rhianna'}, {'sort_name': 'Riannah', 'name': 'Riannah'}, {'sort_name': 'Fenty, Robyn Rihanna', 'name': 'Robyn Rihanna Fenty'}, {'sort_name': 'Rihanna', 'name': 'Rihanna'}], 'gid': '73e5e69d-3554-40d8-8516-00cb38737a1c', '_id': ObjectId('5d21aa8508fd2f5b6dd12654'), 'gender': 'Female', 'type': 'Person', 'sort_name': 'Rihanna', 'area': 'New York', 'begin': {'date': 20, 'month': 2, 'year': 1988}, 'id': 262731, 'tags': [{'count': 1, 'value': 'rnb'}, {'count': 3, 'value': 'barbadian'}, {'count': 1, 'value': 'pop and chart'}, {'count': 1, 'value': 'r&b'}, {'count': 2, 'value': 'dancehall'}, {'count': 1, 'value': 'reggae'}, {'count': 2, 'value': 'hip hop'}, {'count': 1, 'value': 'dance'}, {'count': 2, 'value': 'dance-pop'}, {'count': 4, 'value': 'pop'}, {'count': 1, 'value': 'barbade'}, {'count': 1, 'value': 'barbadien'}, {'count': 1, 'value': 'contemporary r b'}, {'count': 1, 'value': 'barbados'}, {'count': 1, 'value': 'rehab'}], 'name': 'Rihanna', 'ended': True}
{'rating': {'count': 13, 'value': 83}, 'aliases': [{'sort_name': 'Bretney Spears', 'name': 'Bretney Spears'}, {'sort_name': 'B. Spears', 'name': 'B. Spears'}, {'sort_name': 'Brittany Spears', 'name': 'Brittany Spears'}, {'sort_name': 'Briteny Spears', 'name': 'Briteny Spears'}, {'sort_name': 'Brittney Spears', 'name': 'Brittney Spears'}, {'sort_name': 'Spears, Britney Jean', 'name': 'Britney Jean Spears'}], 'gid': '45a663b5-b1cb-4a91-bff6-2bef7bbfdd76', '_id': ObjectId('5d21aa5408fd2f5b6dc5bc78'), 'gender': 'Female', 'type': 'Person', 'sort_name': 'Spears, Britney', 'area': 'United States', 'begin': {'date': 2, 'month': 12, 'year': 1981}, 'id': 791, 'tags': [{'count': 7, 'value': 'pop'}, {'count': 1, 'value': 'américain'}, {'count': 1, 'value': 'electropop'}, {'count': 1, 'value': 'usa'}, {'count': 1, 'value': 'pop and chart'}, {'count': 1, 'value': 'dance-pop'}, {'count': 1, 'value': 'urban pop'}, {'count': 1, 'value': 'if you seek amy'}, {'count': 1, 'value': 'dance'}, {'count': 2, 'value': 'american'}], 'name': 'Britney Spears', 'ended': True}
{'rating': {'count': 11, 'value': 60}, 'aliases': [{'sort_name': 'marron 5', 'name': 'marron 5'}, {'sort_name': 'マルーン５', 'name': 'マルーン５'}, {'sort_name': 'Maroon5', 'name': 'Maroon5'}], 'gid': '0ab49580-c84f-44d4-875f-d83760ea2cfe', '_id': ObjectId('5d21aa8508fd2f5b6dd12e81'), 'id': 66179, 'type': 'Group', 'sort_name': 'Maroon 5', 'area': 'United States', 'begin': {'year': 2002}, 'tags': [{'count': 1, 'value': 'rock and indie'}, {'count': 1, 'value': 'slow pop'}, {'count': 1, 'value': 'automod ng'}, {'count': 1, 'value': 'pop'}, {'count': 1, 'value': 'rock'}, {'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'pop/rock'}, {'count': 1, 'value': 'fixme label mess'}], 'name': 'Maroon 5', 'ended': True}
{'rating': {'count': 7, 'value': 100}, 'gid': 'e942594a-91cc-427a-8beb-6815c28e9254', '_id': ObjectId('5d21aa6408fd2f5b6dc99215'), 'gender': 'Male', 'type': 'Person', 'sort_name': 'Lambert, Adam', 'area': 'United States', 'begin': {'date': 29, 'month': 1, 'year': 1982}, 'id': 627661, 'tags': [{'count': 1, 'value': 'vocalist'}, {'count': 1, 'value': 'glam'}, {'count': 1, 'value': 'costume'}, {'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'showman'}, {'count': 1, 'value': 'rock'}, {'count': 1, 'value': 'pop'}, {'count': 1, 'value': 'american idol'}], 'name': 'Adam Lambert', 'ended': True}
{'rating': {'count': 7, 'value': 77}, 'aliases': [{'sort_name': 'ファットボーイ・スリム', 'name': 'ファットボーイ・スリム'}, {'sort_name': 'Fatboy Slim - Because We Can', 'name': 'Fatboy Slim - Because We Can'}, {'sort_name': 'Fatboy Slin', 'name': 'Fatboy Slin'}, {'sort_name': 'Fat Boy Slim', 'name': 'Fat Boy Slim'}], 'gid': '34c63966-445c-4613-afe1-4f0e1e53ae9a', '_id': ObjectId('5d21aa7308fd2f5b6dccfb0f'), 'gender': 'Male', 'type': 'Person', 'sort_name': 'Fatboy Slim', 'area': 'United Kingdom', 'begin': {'date': 31, 'month': 7, 'year': 1963}, 'id': 255, 'tags': [{'count': 1, 'value': 'trip hop'}, {'count': 3, 'value': 'electronic'}, {'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'trip-hop'}, {'count': 1, 'value': 'english'}, {'count': 1, 'value': 'classic pop and rock'}, {'count': 2, 'value': 'uk'}, {'count': 2, 'value': 'big beat'}, {'count': 1, 'value': 'britannique'}, {'count': 3, 'value': 'british'}, {'count': 1, 'value': '1998'}], 'name': 'Fatboy Slim', 'ended': True}
{'rating': {'count': 6, 'value': 83}, 'aliases': [{'sort_name': 'Basementt Jaxx', 'name': 'Basementt Jaxx'}, {'sort_name': 'Basment Jaxx', 'name': 'Basment Jaxx'}, {'sort_name': 'Basemant Jaxx', 'name': 'Basemant Jaxx'}, {'sort_name': 'Bassment Jaxx', 'name': 'Bassment Jaxx'}, {'sort_name': 'Basement Jazz', 'name': 'Basement Jazz'}, {'sort_name': 'Basements Jaxx', 'name': 'Basements Jaxx'}], 'gid': '28cbf94d-0700-4095-a188-37e373b069a7', '_id': ObjectId('5d21aa7808fd2f5b6dce4655'), 'id': 1060, 'type': 'Group', 'sort_name': 'Basement Jaxx', 'area': 'United Kingdom', 'begin': {'year': 1994}, 'tags': [{'count': 1, 'value': 'english'}, {'count': 2, 'value': 'uk'}, {'count': 1, 'value': 'house'}, {'count': 1, 'value': 'uk garage'}, {'count': 3, 'value': 'dance'}, {'count': 4, 'value': 'british'}, {'count': 1, 'value': 'dance and electronica'}, {'count': 1, 'value': '10s'}, {'count': 2, 'value': 'electronic'}, {'count': 1, 'value': '00s'}, {'count': 1, 'value': '90s'}], 'name': 'Basement Jaxx', 'ended': True}
{'rating': {'count': 5, 'value': 68}, 'aliases': [{'sort_name': 'Conershop', 'name': 'Conershop'}, {'sort_name': 'Corner Shop -', 'name': 'Corner Shop -'}, {'sort_name': 'Cornership', 'name': 'Cornership'}, {'sort_name': 'Corner Shop', 'name': 'Corner Shop'}], 'gid': '92046be7-0927-4835-a4ed-a90416747d53', '_id': ObjectId('5d21aa7708fd2f5b6dce1434'), 'id': 798, 'type': 'Group', 'sort_name': 'Cornershop', 'area': 'United Kingdom', 'begin': {'year': 1991}, 'tags': [{'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'indie'}, {'count': 1, 'value': 'brit pop'}, {'count': 1, 'value': 'indian'}, {'count': 2, 'value': 'british'}, {'count': 1, 'value': 'uk'}, {'count': 1, 'value': 'asian'}, {'count': 1, 'value': 'british asian'}, {'count': 1, 'value': 'english'}, {'count': 1, 'value': 'rock and indie'}], 'name': 'Cornershop', 'ended': True}
'''